export const tsConfig = {
    compilerOptions: {
        rootDir: "./src",
        outDir: "./dist",
        module: "nodenext",
        moduleResolution: "nodenext",
        target: "esnext",
        esModuleInterop: true,
        types: ["node"],
        sourceMap: true,
        declaration: true,
        declarationMap: true,
        strict: true,
        skipLibCheck: true,
        experimentalDecorators: true,
        emitDecoratorMetadata: true,
        strictPropertyInitialization: false,
    },
    include: ["src/**/*"],
    exclude: ["node_modules", "dist"],
};
